package tech.mineapp.model.response;

import lombok.Data;

/**
 * A Container for all requests, contains metadata about a response
 * generated by the server
 * 
 * @author amolmoses
 */
@Data
public class ContainerResponseModel {
	private String verb;
	private String endpoint;
	private String status;
	private String errorMessage;
	
	private ResponseModel responseObject;
}
